In [ ]:
#!pip install tensorflow
#!pip install --upgrade pip

In [4]:
import tensorflow as tf

In [3]:
tf.__version__

'2.10.0'

In [4]:
hello = tf.constant("Hello, Tensor Flow!")

In [5]:
print(hello)

tf.Tensor(b'Hello, Tensor Flow!', shape=(), dtype=string)


# Operações Matemáticas com Tensores

## Soma

In [5]:
# Contantes
const_a = tf.constant(5)
const_b = tf.constant(9)

In [6]:
print(const_a, const_b)

tf.Tensor(5, shape=(), dtype=int32) tf.Tensor(9, shape=(), dtype=int32)


In [7]:
# Soma
total = const_b + const_a

In [8]:
print(total)

tf.Tensor(14, shape=(), dtype=int32)


In [9]:
# Criando os nodes no grafo computacional
node1 = tf.constant(5, dtype = tf.int32)
node2 = tf.constant(9, dtype = tf.int32)
node3 = tf.add(node1, node2)

# Executa o grafo
print(f"\nA soma do node1 com o node2 é: {node3}")


A soma do node1 com o node2 é: 14


## Subtração

In [10]:
# Tensores randômicos
rand_a = tf.random.normal([3], 2.0)
rand_b = tf.random.normal([3], 1.0, 4.0)

In [11]:
print(rand_a)
print(rand_b)

tf.Tensor([-0.6317804  1.7159085  1.566599 ], shape=(3,), dtype=float32)
tf.Tensor([-3.069655   2.2090158 -2.8506088], shape=(3,), dtype=float32)


In [12]:
# Subtração 
sub = tf.subtract(rand_a, rand_b)

In [13]:
print(sub)
type(sub)

tf.Tensor([ 2.4378746  -0.49310732  4.4172077 ], shape=(3,), dtype=float32)


tensorflow.python.framework.ops.EagerTensor

## Divisão

In [14]:
node1 = tf.constant(21,dtype=tf.int32)
node2 = tf.constant(7, dtype=tf.int32)

In [15]:
# Divisão
div = tf.math.truediv(node1, node2)
print(f"A divisão entre os tensores é: \n {div}")

A divisão entre os tensores é: 
 3.0


In [16]:
print(div)

tf.Tensor(3.0, shape=(), dtype=float64)


## Multiplicação

In [17]:
# Criando tensores
tensor_a = tf.constant([[4., 2.]])
tensor_b = tf.constant([[3.],[7.]])

In [18]:
print(tensor_a)
print(tensor_b)

tf.Tensor([[4. 2.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[3.]
 [7.]], shape=(2, 1), dtype=float32)


In [19]:
# Multiplicação 
prod = tf.math.multiply(tensor_a, tensor_b)

In [20]:
print(prod)

tf.Tensor(
[[12.  6.]
 [28. 14.]], shape=(2, 2), dtype=float32)


In [21]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [22]:
print(mat_a)
print(mat_b)

tf.Tensor(
[[2 3]
 [9 2]
 [4 5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[6 4 5]
 [3 7 2]], shape=(2, 3), dtype=int32)


In [23]:
# Multiplicação
mat_prod = tf.linalg.matmul(mat_a, mat_b)

In [24]:
print(mat_prod)

tf.Tensor(
[[21 29 16]
 [60 50 49]
 [39 51 30]], shape=(3, 3), dtype=int32)


## Usando variáveis

In [25]:
# Criando o mesmo tensor com tf.Variable() e tf.constant()
tensor_mutavel = tf.Variable([10, 7])
tensor_imutavel = tf.constant([10,7])
tensor_mutavel, tensor_imutavel

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [26]:
# Utilizando o metodo assing() para mudar um tensor variavel
tensor_mutavel[0] = 7
tensor_mutavel

TypeError: 'ResourceVariable' object does not support item assignment

In [27]:
tensor_mutavel[0].assign(7)
tensor_mutavel

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

# **NÃO SE PODE ALTERAR UM TENSOR CRIADO COM tf.constant()**

# Obs: Na maioria das vezes o Tensor Flow escolhe automaticamente se vai usar tensor variavel ou constante, ao carregar ou modelar dados.

In [29]:
# Tensor preenchido com 1
tf.ones(shape=(10,3))

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [30]:
# Tensor preenchido com 0
tf.zeros(shape=(20,3))

<tf.Tensor: shape=(20, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [31]:
# Criando um tensor rank 4 (4 DIMENSÕES)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [35]:
# Imprime atributos do tensor
print("Tipo de dado de cada elemeno:", rank_4_tensor.dtype)
print("Número de dimensões (rank):", rank_4_tensor.ndim)
print("Shape do tensor:", rank_4_tensor.shape)
print("Elemento no eixo 0 do tensor: ", rank_4_tensor.shape[0])
print("Elemento no último eixo do tensor:", rank_4_tensor.shape[-1])
print("Número total de elementos (2*3*4*5):", tf.size(rank_4_tensor).numpy())

Tipo de dado de cada elemeno: <dtype: 'float32'>
Número de dimensões (rank): 4
Shape do tensor: (2, 3, 4, 5)
Elemento no eixo 0 do tensor:  2
Elemento no último eixo do tensor: 5
Número total de elementos (2*3*4*5): 120


In [36]:
# Obtém os 2 primeiros itens de cada dimensão
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [37]:
# Obtém a dimensão de cada índice, exceto o final
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
# Criar um tensor de rank 2 (2 dimensões)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])

In [40]:
# Obtém o último item de cada linha
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

# FIM. 